### ISSUE TITLE
failed to fetch user details for oauth: missing auth headers

### ISSUE THREAD

**Issue by pehcastro** [j4w8n/sveltekit-supabase-ssr#3]
while trying to login with twitter as provider (using oauth v1) I receive this:

![image](https://github.com/j4w8n/sveltekit-supabase-ssr/assets/3126796/b8f4c0b4-e78c-4eee-a512-959bd3c868fb)

it redirect me back but I still see the auth page, not the authenticated page

![image](https://github.com/j4w8n/sveltekit-supabase-ssr/assets/3126796/f1f80562-f6a1-4777-84b6-dd9a08176151)

cookies are there, probably the reason why I receive my user data inside the database;

![image](https://github.com/j4w8n/sveltekit-supabase-ssr/assets/3126796/49da420c-0970-4925-bb39-33a001d2ec6f)

also, what is this JWT_SECRET? should I add a JWT_SECRET inside the .env.local? 

![image](https://github.com/j4w8n/sveltekit-supabase-ssr/assets/3126796/33c4c9ef-3040-412d-a0e4-3f8aa6f0d059)

overall, no changes to the code other than the provider from github to twitter, I would like to try to make it work and jump to the svelte.5.0.0.next-1 and test out changes from onMount to $ effect etc with this auth.

**Comment by j4w8n** [comment]
Not having the `JWT_SECRET` in `env.local` is why you're having issues. You can get that from your project, in your Supabase dashboard, at Project Settings > API > JWT Settings - assuming you're using Supabase's hosted instance.

The nav is working because it grabs data from the `supabase.auth.getSession()` call in `src/+layout.ts`. Whereas the rest is getting it from `event.locals.getSession()`, which is returning `null` because the jwt is not being verified correctly without the jwt secret - so SvelteKit is redirecting you back to `/auth`.

**Comment by pehcastro** [comment]
Figured it out, but thanks anyway!
